export const projects =[
  {
    id: "1",
    title: "3D Solar System Planets to Explore",
    blurb: "Explore the wonders of our solar system with this captivating 3D simulation of the planets using Three.js.",
    tags: ["3D", "Space", "Simulation"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 240,
    updatedAt: "2025-08-15",
    thumbnail: "/projectThumb/p1.svg",
    live: "https://ui.earth.com",
    complexity: "advanced",
  },
  {
    id: "2",
    title: "Yoom - Video Conferencing App",
    blurb: "Simplify your video conferencing experience with Yoom. Seamlessly connect with colleagues and friends.",
    tags: ["Video", "Collaboration", "SaaS"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 198,
    updatedAt: "2025-07-29",
    thumbnail: "/projectThumb/p2.svg",
    live: "https://ui.yoom.com",
    complexity: "intermediate",
  },
  {
    id: "3",
    title: "AI Image SaaS - Canva Application",
    blurb: "A REAL SaaS app with AI features and a payments/credits system using the latest stack.",
    tags: ["AI", "SaaS", "Payments"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 321,
    updatedAt: "2025-06-12",
    thumbnail: "/projectThumb/p3.svg",
    live: "https://ui.aiimg.com",
    complexity: "beginner",
  },
  {
    id: "4",
    title: "Animated Apple iPhone 3D Website",
    blurb: "Recreated the Apple iPhone 15 Pro website, combining GSAP animations and Three.js 3D effects.",
    tags: ["3D", "Animation", "GSAP"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 287,
    updatedAt: "2025-08-02",
    thumbnail: "/projectThumb/p4.svg",
    live: "https://ui.apple.com",
    complexity: "advanced",
  },
  {
    id: "5",
    title: "3D Solar System Planets to Explore",
    blurb: "Explore the wonders of our solar system with this captivating 3D simulation of the planets using Three.js.",
    tags: ["3D", "Space", "Simulation"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 240,
    updatedAt: "2025-08-15",
    thumbnail: "/projectThumb/p1.svg",
    live: "https://ui.earth.com",
    complexity: "advanced",
  },
  {
    id: "6",
    title: "Yoom - Video Conferencing App",
    blurb: "Simplify your video conferencing experience with Yoom. Seamlessly connect with colleagues and friends.",
    tags: ["Video", "Collaboration", "SaaS"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 198,
    updatedAt: "2025-07-29",
    thumbnail: "/projectThumb/p2.svg",
    live: "https://ui.yoom.com",
    complexity: "intermediate",
  },
  {
    id: "7",
    title: "AI Image SaaS - Canva Application",
    blurb: "A REAL SaaS app with AI features and a payments/credits system using the latest stack.",
    tags: ["AI", "SaaS", "Payments"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 321,
    updatedAt: "2025-06-12",
    thumbnail: "/projectThumb/p3.svg",
    live: "https://ui.aiimg.com",
    complexity: "beginner",
  },
  {
    id: "8",
    title: "Animated Apple iPhone 3D Website",
    blurb: "Recreated the Apple iPhone 15 Pro website, combining GSAP animations and Three.js 3D effects.",
    tags: ["3D", "Animation", "GSAP"],
    tech: ["/technologiesIcons/next.svg", "/technologiesIcons/tail.svg", "/technologiesIcons/ts.svg", "/technologiesIcons/three.svg", "/technologiesIcons/gsap.svg"],
    stars: 287,
    updatedAt: "2025-08-02",
    thumbnail: "/projectThumb/p4.svg",
    live: "https://ui.apple.com",
    complexity: "advanced",
  },
];